@echo off
echo Adding files...
git add .
echo Committing changes...
git commit -m "Final: Implemented premium theme-aware styling, skeletons, custom form controls, and resolved hydration/missing module errors"
echo Setting up branch...
git branch -M main
echo Removing old remote...
git remote remove origin >nul 2>&1
echo Adding new remote...
git remote add origin "https://github.com/codoacademy/zeequeplus-web.git"
echo Pushing to GitHub...
git push -u origin main
